trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-20.04'

stages:   
- stage: Deploy_Stage
  displayName: Deploy Azure App Service
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs: 
    - job: Deploy_Microservice
      steps:
      - checkout: self 
      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: demo-cloudsquad-svc
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az webapp deployment slot swap -g demo-cloudsquad -n demo-cloudsquad-app --slot develop --target-slot production